### ISSUE TITLE
Supervisor error: Could not fetch changelog

### ISSUE THREAD

**Issue by Failure404** [Triangulix/HomeAssistant_AddOns#1]
Hi and thank you for your add-on, it solves an elementary problem for me.
Unfortunately, with today's update of supervisor to supervisor-2024.04.4, I am continously getting the following error:

ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /addons/ce7e09fa_sox_play/changelog request 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('[http://172.30.32.2/addons/ce7e09fa_sox_play/changelog']

WARNING (MainThread) [homeassistant.components.hassio.data] Could not fetch changelog for ce7e09fa_sox_play: #033[0m

I hope this can be resolved.
Thx in advance

**Comment by Triangulix** [comment]
Thanks,

I'll look into it.

**Comment by Triangulix** [comment]
Solved. I also added a bit to the readme since the examples now require the right slug
